# Generated by Django 5.0.7 on 2024-07-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_user_passwd_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(default='よろしくお願いします。'),
        ),
    ]
