# Generated by Django 5.0.7 on 2024-07-23 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
