# Generated by Django 5.0.7 on 2024-07-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_user_icon_remove_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='default_icon.png', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.TextField(default='よろしくお願いします。'),
        ),
    ]
