# Generated by Django 5.0.7 on 2024-07-23 04:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_user_icon_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timeslot',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
