# Generated by Django 5.0.7 on 2024-07-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
