# Generated by Django 5.0.7 on 2024-07-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='blog/icon/default_icon.png', upload_to='blog/icon/'),
        ),
    ]
