# Generated by Django 5.0.7 on 2024-07-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_user_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(default='Nice to meet you!'),
        ),
    ]
