# Generated by Django 5.0.7 on 2024-07-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_user_login_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='default_login_value', max_length=20),
        ),
    ]
